"""Corpora."""
from .corpora import (celex_english,
                      celex_dutch,
                      celex_german,
                      cmu,
                      subtlex,
                      bpal,
                      lexique,
                      wordnet,
                      elp,
                      blp,
                      flp,
                      dlp1,
                      dlp2,
                      klp,
                      clp,
                      subtlexnl,
                      subtlexuk,
                      subtlexus,
                      subtlexzh)

from .base import reader

__all__ = ["celex_english",
           "celex_dutch",
           "celex_german",
           "cmu",
           "subtlex",
           "bpal",
           "lexique",
           "wordnet",
           "elp",
           "blp",
           "flp",
           "dlp1",
           "dlp2",
           "klp",
           "clp",
           "subtlexde",
           "subtlexnl",
           "subtlexuk",
           "subtlexus",
           "subtlexzh",
           "reader"]
